export const SET_MENU="SET_MENU";
export const BEGIN_SET_MENU="BEGIN_SET_MENU";
export const SUCCESS_SET_MENU="SUCCESS_SET_MENU";
export const ADD_TO_COMPARISON="ADD_TO_COMPARISON";
export const REMOVE_COMPARISON_ITEM = "REMOVE_COMPARISON_ITEM";
export const REMOVE_ALL="REMOVE_ALL";
export const ADD_TO_COMMENT="ADD_TO_COMMENT";
// REQUEST FIREBASE LOGIN
export const BEGIN_LOGIN_REQUEST = "BEGIN_LOGIN_REQUEST";
export const SUCCESS_LOGIN_REQUEST = "SUCCESS_LOGIN_REQUEST";
export const FAIL_LOGIN_REQUEST = "FAIL_LOGIN_REQUEST";
export const REMEMBER_LOGIN = "REMEMBER_LOGIN";

// REQUEST FIREBASE REGISTER
export const BEGIN_REGISTER_REQUEST = "BEGIN_REGISTER_REQUEST";
export const SUCCESS_REGISTER_REQUEST = "SUCCESS_REGISTER_REQUEST";
export const FAIL_REGISTER_REQUEST = "FAIL_REGISTER_REQUEST";

// UPDATE USER INFO
export const BEGIN_UPDATE_USERINFO = "BEGIN_UPDATE_USERINFO";
export const SUCCESS_UPDATE_USERINFO = "SUCCESS_UPDATE_USERINFO";
export const FAIL_UPDATE_USERINFO = "FAIL_UPDATE_USERINFO";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

//COMMENT
export const ADD_COMMENT = "ADD_COMMENT";
export const GET_COMMENT = "GET_COMMENT";
export const BEGIN_COMMENT="BEGIN_COMMENT";
export const SUCCESS_COMMENT="SUCCESS_COMMENT";
export const BEGIN_ADD_COMMENT="BEGIN_ADD_COMMENT";
export const SUCCESS_ADD_COMMENT="SUCCESS_ADD_COMMENT";
//FAVORITE
export const ADD_FAVORITE = "ADD_FAVORITE";
export const GET_FAVORITE = "GET_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const GET_SINGLE_FAVORITE= "GET_SINGLE_FAVORITE";
export const BEGIN_ADD_FAVORITE="BEGIN_ADD_FAVORITE";
export const SUCCESS_ADD_FAVORITE="SUCCESS_ADD_FAVORITE";