export const SET_MENU="SET_MENU";
export const ADD_TO_COMPARISON="ADD_TO_COMPARISON";
export const REMOVE_COMPARISON_ITEM = "REMOVE_COMPARISON_ITEM";
export const REMOVE_ALL="REMOVE_ALL";
export const ADD_TO_COMMENT="ADD_TO_COMMENT";